package hibernate.entities;
// Generated Nov 3, 2018 12:51:33 PM by Hibernate Tools 5.2.11.Final

import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.PrePersist;
import javax.persistence.PreUpdate;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;

/**
 * User generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "USER", uniqueConstraints = { @UniqueConstraint(columnNames = "EMAIL"),
		@UniqueConstraint(columnNames = "LOGIN") })
public class User implements Serializable {

	private Long id;
	private String login;
	private String email;
	private String password;
	private String role;
	private Timestamp createTime;
	private Timestamp modifyTime;

	public User() {
	}

	public User(Long id, String login, String email, String password, String role) {
		this(id, login, email, password);
		this.role = role;
	}

	public User(Long id, String login, String email, String password) {
		this.id = id;
		this.login = login;
		this.email = email;
		this.password = password;
	}

	@PrePersist
	private void preInsert() {
		if (this.role == null) {
			this.role = "USER";
		}
	}

	@PreUpdate
	private void preUpdate() {
		this.preInsert();
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "LOGIN", unique = true, nullable = false, length = 2000000000)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "EMAIL", unique = true, nullable = false, length = 2000000000)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "PASSWORD", nullable = false, length = 2000000000)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "ROLE", nullable = false, length = 2000000000)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@CreationTimestamp
	@Column(name = "CREATE_TIME", length = 2000000000)
	public Timestamp getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Timestamp createTime) {
		this.createTime = createTime;
	}

	@UpdateTimestamp
	@Column(name = "MODIFY_TIME", length = 2000000000)
	public Timestamp getModifyTime() {
		return this.modifyTime;
	}

	public void setModifyTime(Timestamp modifyTime) {
		this.modifyTime = modifyTime;
	}

}
